### ISSUE TITLE
FrozenPbList is not a subtype of type PbList

### ISSUE THREAD

**Issue by korzonkiee** [fluttercommunity/firebase_dart_sdk#14]
Hi!

First of all, thanks for your work. I really appreciate it.

I've been playing with the cloud_firestore_vm example and I've stumbled upon the following exception when trying to add new a document to a Firestore collection:

```
E/flutter (15589): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'FrozenPbList<Write>' is not a subtype of type 'PbList<dynamic>' in type cast
E/flutter (15589): #0      _writeToProto3Json 
package:protobuf/…/protobuf/proto3_json.dart:102
E/flutter (15589): #1      GeneratedMessage.toProto3Json 
package:protobuf/…/protobuf/generated_message.dart:221
E/flutter (15589): #2      BaseStream.writeRequest 
package:cloud_firestore_vm/…/datastore/base_stream.dart:80
E/flutter (15589): #3      WriteStream.writeMutations 
package:cloud_firestore_vm/…/datastore/write_stream.dart:127
E/flutter (15589): #4      RemoteStore._handleWriteStreamHandshakeComplete 
package:cloud_firestore_vm/…/remote/remote_store.dart:518
E/flutter (15589): <asynchronous suspension>
E/flutter (15589): #5      RemoteStore._writeEvents 
package:cloud_firestore_vm/…/remote/remote_store.dart:449
E/flutter (15589): #6      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (15589): #7      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (15589): #8      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (15589): #9      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter (15589): #10     _DelayedData.perform  (dart:async/stream_impl.dart:594:14)
E/flutter (15589): #11     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:710:11)
E/flutter (15589): #12     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:670:7)
E/flutter (15589): #13     _rootRun  (dart:async/zone.dart:1180:38)
E/flutter (15589): #14     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (15589): #15     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (15589): #16     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter (15589): #17     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (15589): #18     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (15589): #19     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (15589): #20     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter (15589): #21     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (15589): #22     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
```

As the exception says, a `FrozenPbList` type is not a subtype of `PbList`. In fact, after looking at the source code of the protobuf library, it is a subtype of `PbListBase`.

```
class FrozenPbList<E> extends PbListBase<E> 
```
https://github.com/dart-lang/protobuf/blob/master/protobuf/lib/src/protobuf/pb_list.dart#L9

I've modified the source code of the protobuf library by changing the cast to `PbListBase` and everything seems to work as expected - document writes are successfully reflected in the Firestore database.

I assume that changing the underlying protobuf library is not an ideal solution to the problem, hence I wonder if there is anything in the cloud_firestore library that might cause the issue.

I'm running the cloud_firestore_vm example in the following environment:

Flutter v1.18.0-dev.5.0
Mac OS X 10.15.3 19D76
Xiaomi Mi A2 Lite & iPhone 8 Plus

**Comment by long1eu** [comment]
Hey! Sorry for not responding. I also faced that issues and it seems it's an issue with protobuf that they fixed. Can you check you are on the latest version?
